### ISSUE TITLE
URL box jumps to top when clicked in

### ISSUE THREAD

**Issue by SWannell** [SWannell/tracked-link-builder#20]
From commit https://github.com/SWannell/tracked-link-builder/blob/57ba66ef7d18e863a3efefdcf2d386dd338f3075/HTML%20builder#L1604

When a user clicks into the URL box, the focus jumps to the top of the box. If you are trying to highlight the third URL in a list, it becomes impossible without expanding the URL box.

It's there because:

- If a user selects 4 audiences from one drop-down
- And then they remove two via clicking the \D7 (cross)
- Then on the first removal-click the URL doesn't change
- And on the second removal-click the URL changes to acknowledge the first removal-click

So something was needed to update the URLs before someone clicks them to copy them out. However, if that issue is resolved, this line could be removed.

**Comment by SWannell** [comment]
Linked issue = user report:

> It can be difficult to copy the generated URL. (can't right-click to copy, highlighting doesn't work, try to Ctrl+C but doesn't copy)

**Comment by SWannell** [comment]
Need front-end dev help

**Comment by raphaelleRC** [comment]
I changed the "readonly" property in the textarea to "disabled". They still won't be able to edit the content but should be able to select whatever they want now
